# Site settings
title: "Ames Turner"
description: "Ames' Blog"
url: "https://jeppeport.github.io"   # Change to your GitHub Pages URL
baseurl: ""                              # For user/organization site (or "/reponame" for project site)

# Build Settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# Theme
remote_theme: erlzhang/jekyll-theme-persephone
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate

# Exclude files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

nav:
  - name: Home
    link: /
  - name: About
    link: /about/