# Site settings
title: "Ames Turner"
description: "Ames' Blog"

author: "Ames Turner"

social:
  github: jeppeport

# Theme
remote_theme: erlzhang/jekyll-theme-persephone
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate

# Exclude files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

theme_setting:
  blog_page: "blog.md"
  about_page: "about.md"
  archive_page: "archive.md"

  nav_pages:
    - name: Home
      link: /
    - name: About
      link: /about/
    - name: Blog
      link: /blog/

  code: true
  math: true

rss: "/feed.xml"