# Site settings
title: "Ames Turner"
description: "Ames' Blog"



author: "Ames Turner"


# Theme
remote_theme: erlzhang/jekyll-theme-persephone
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate

# Exclude files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

theme_setting:
  blog_page: "blog/index.md"
  about_page: "about.md"
  archive_page: "archive.md"

  nav:
    - "about.md"

  code: true
  math: true